---
abstract: 'Read config files containing hashes'
author:
  - 'Erik Carlsson <csson@cpan.org>'
build_requires:
  Test::Deep: '0.110'
  Test::Exception: '0.31'
  Test::More: '0.96'
  Test::Pod: '1.45'
configure_requires:
  Module::Build::Tiny: '0.037'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Config-FromHash
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  File::Basename: '0'
  File::Slurp: '9999.19'
  Hash::Merge: '0.200'
  experimental: '0.008'
  perl: '5.020'
resources:
  bugtracker: https://github.com/Csson/config-fromhash/issues
  homepage: https://github.com/Csson/config-fromhash
  repository: https://github.com/Csson/config-fromhash.git
version: '0.06'
