---
abstract: 'Read config files with hashes'
author:
  - 'Erik Carlsson <csson@cpan.org>'
build_requires:
  Test::More: '0.96'
configure_requires:
  Module::Build::Tiny: '0.036'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Config-FromHash
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  File::Basename: '0'
  Hash::Merge: '0.200'
  perl: '5.010'
resources:
  bugtracker: https://github.com/Csson/config-fromhash/issues
  homepage: https://github.com/Csson/config-fromhash
  repository: https://github.com/Csson/config-fromhash.git
version: '0.01'
